import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import "./globals.css";
import { pageFetcher } from "@/lib/data";

import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";

const anuphan = Anuphan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navItems = await pageFetcher("navigation-bar");

  return (
    <html lang="en">
      <body className={anuphan.className}>
        <NavBar navItems={navItems} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
